services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - ./Backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./Fontend/my-project
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
